# Generated by Django 4.0.5 on 2022-07-19 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_post_liked_alter_comment_user_alter_like_post_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='image',
            new_name='img',
        ),
    ]
